### ISSUE TITLE
Wie seit ihr an die Question Struktur für GraphQL gekommen?

### ISSUE THREAD

**Issue by lineick** [DAMcraft/gutefrage#1]
Hi :),

Ich hätte da mal eine Frage:
Ihr nutzt ja GraphQL um die Inhalte aller Frage-Attribute auszulesen. Wie habt ihr es geschafft an die Frage-Struktur und die dazugehörigen Attribute zu kommen und werden bei der GraphQL-Abfrage alle Attribute einer Question abgefragt?

**Comment by lina-x64** [comment]
Habe die requests mit alle manuell überprüft (Das geht zum beispiel alleine schon mit den Chrome oder Firefox devtools)
